### ISSUE TITLE
Add support for PostgreSQL and use it as default database

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-docker#21]
Currently the Dockerfiles contain configuration for MySQL and Oracle. We should add support for PostgreSQL and prepare DDL for the whole PowerAuth stack.

**Comment by petrdvorak** [comment]
This one can wait for the next release. Currently, it seems that we are OK with the engines we support. Generally, we need to support:

- Oracle
- PostrgreSQL
- MySQL
- MSSQL

**Comment by petrdvorak** [comment]
... but this does not have to be translated in Docker image, we can only live with one main and one additional DB in Docker (MySQL and Oracle, just as we have it).

**Comment by petrdvorak** [comment]
Just to comment on this... PostgreSQL became so much superior to MySQL that we should probably have the default images ready in PostgreSQL and be ready for Oracle.

Optionally, we can also have support for MySQL. We should avoid MSSQL since the database is really poorly performing in the strict locking department.

**Comment by romanstrobl** [comment]
I will switch the default database in Docker images to PostgreSQL for the next release.
